api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: [ 'application/json' ]
        jsonld: [ 'application/ld+json' ]
        jsonhal: [ 'application/hal+json' ]
        jsonapi: [ 'application/vnd.api+json' ]
        xml: [ 'application/xml', 'text/xml' ]
        yaml: [ 'application/x-yaml' ]
        csv: [ 'text/csv' ]
        html: [ 'text/html' ]
        stateless: true
    swagger:
        versions: [3]

    enable_swagger_ui: true
    enable_re_doc: false
